### ISSUE TITLE
Add in generic rules

### ISSUE THREAD

**Issue by wired84** [504rules/504rules.github.io#28] opened 2015-10-30 11:00 UTC
Not sure how easy this would be, but the two pages of generic rules from the start of the main rulebook would be useful to include where applicable - there are some modules that overwrite these rules but in general they are needed for ever game. Whilst I know most of those basic ones, it'd be great for new players to be able to see and read. If not just a link to basic rules would be great

**Comment by Arachnid** [comment] 2015-10-30 11:03
Duplicate of #18.

**Closed as completed by Arachnid** 2015-10-30 11:03 UTC
