### ISSUE TITLE
Privileges don't print

### ISSUE THREAD

**Issue by wcraigtrader** [504rules/504rules.github.io#107] opened 2016-02-24 17:10 UTC
Maybe this is by design, but when I try to print a world that uses privileges (eg: 123), the privileges section doesn't get printed.  This happens consistently in these browsers:
- Mac OS X, Chrome 48.0.2564.109
- Mac OS X, Firefox 44.0.2
- Mac OX X, Safari 9.0.3
- Linux, Chrome 48.0.2564.116
- Linux, Firefox 38.6.1

**Comment by OsnaFonz** [comment] 2016-02-24 17:41
At the moment it's really by design to keep most of the rules sets on two pages. I will soon add a option to print this section too.

**Comment by wcraigtrader** [comment] 2016-02-25 14:42
Well, even without printed privileges, this is still a wonderful resource.  Thanks for putting in all of the hard work to create and maintain it.

**Comment by refactoringdr** [comment] 2016-11-02 20:16
Pull request has been merged

**Closed as completed by refactoringdr** 2016-11-02 20:16 UTC
